on:
  workflow_dispatch:
  #push:
  #  branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      #- name: Install R Dependencies
      #  run: |
      #    y | Rscript --vanilla src/install_packages.R
      - name: Install Quarto Tex
        run: quarto install tool tinytex
      - name: Install pandoc
        run: |
          mkdir Downloads && cd Downloads
          wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
          sudo dpkg -i pandoc-2.19.2-1-amd64.deb          
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypandoc jupytext bibtexparser python-frontmatter
      # - name: Convert Files to Markdown
      #   run: |
      #     echo "Compiling and Converting Events"
      #     python src/compile_events.py
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: crress/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
